[embedding]
base_url = "http://localhost:8001/v1"
model = "jina-embeddings-v5-text-small"

[llm]
base_url = "http://localhost:8801/v1"
model = "gpt-5.2"

[rerank]
base_url = "http://localhost:8001/v1"
model = "jina-reranker-v3"

[visual]
base_url = "http://localhost:8003/v1"
model = "qwen2.5-vl-3b-instruct"


[embedding-1]
base_url = "http://100.70.159.64:1234/v1"
model = "text-embedding-embedding-gemma-300m"

[llm-1]
base_url = "http://100.83.31.44:1234/v1"
model = "qwen2.5-7b-instruct"

[rerank-1]
# Example: same or different server
# base_url = "http://100.70.159.64:1234/v1"
# model = "rerank-model-name"

[visual-1]
base_url = "http://100.89.202.61:1234/v1"
model = "qwen2.5-vl-3b-instruct"
